### ISSUE TITLE
Speedrun Leaderboard Question

### ISSUE THREAD

**Issue by lanran2001** [UrFriendKen/PlateUpMoreSpeedrunInfo#1]
Why is my statistics in the game differ from the leaderboard in the mod? I played Speedrun on May 20th, 2023, but even the seed is different.
![image](https://github.com/UrFriendKen/PlateUpMoreSpeedrunInfo/assets/32696633/006dbf58-7d5c-4b29-88a7-f35a45de571b)
![image](https://github.com/UrFriendKen/PlateUpMoreSpeedrunInfo/assets/32696633/0e2c4820-37ac-4f34-b5d4-ff4fbf372132)

**Comment by UrFriendKen** [comment]
Yea. I did realize something changed, I have a copy of all the seeds but I don't intend to hardcode them. Will fix it sometime.

**Comment by UrFriendKen** [comment]
Anyways the high percentile is likely due to you having mods, including this one, installed while doing the run. Runs with mods are not submitted to the leaderboard

**Comment by lanran2001** [comment]
thx :)
